version: '3.7'

networks:
    monitor-network:
      name: monitor-network

services:
  monitor-prometheus:
    build: ./prometheus
    container_name: monitor-prometheus
    labels:
      container_group: monitor
    ports:
      - 9090:9090
    networks:
      - monitor-network

  monitor-grafana:
    build: ./grafana
    container_name: monitor-grafana
    labels:
      container_group: monitor
    ports:
      - 3000:3000
    networks:
      - monitor-network

  monitor-node-exporter:
    image: prom/node-exporter:latest
    container_name: monitor-node-exporter
    restart: always
    labels:
      container_group: monitor
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    expose:
      - 9100
    networks:
      - monitor-network

  monitor-cadvisor:
    image: google/cadvisor:latest
    container_name: monitor-cadvisor
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    labels:
      container_group: monitor
    networks:
      - monitor-network