global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: node
  static_configs:
  - targets:
    - monitor-node-exporter:9100
- job_name: containers
  scrape_interval: 10s
  scrape_timeout: 5s
  static_configs:
  - targets: 
    - monitor-cadvisor:8080